import Head from 'next/head';
import Link from 'next/link';

import { supabase } from 'utils/supabase';

export default function Home({ lessons }) {
  return (
    <div>
      <Head>
        <title>FlexIt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        {lessons.map((item) => (
          <Link key={item.id} href={`/${item.id}`}>
            <a className="m-2 border-2 p-2 bg-slate-500">
              <h4>{item.title}</h4>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const { data: lessons } = await supabase.from('lesson').select('*');
  return {
    props: {
      lessons,
    },
  };
}
